'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const root = path.join(__dirname, '..', '..');
const read = (relativePath) => fs.readFileSync(path.join(root, relativePath), 'utf8');

test('phone input layer is loaded by every page that owns a phone form', () => {
    assert.match(read('public/index.html'), /core\/phone-inputs\.js\?v=7/);
    assert.match(read('public/register-gym.html'), /core\/phone-inputs\.js\?v=7/);
    assert.match(read('public/register-trainer.html'), /core\/phone-inputs\.js\?v=7/);
    assert.match(read('public/trainer-workspace.html'), /core\/phone-inputs\.js\?v=7/);
    assert.doesNotMatch(read('public/index.html'), /data-default-country="EG"/);
    assert.doesNotMatch(read('public/register-gym.html'), /data-default-country="EG"/);
    assert.doesNotMatch(read('public/register-trainer.html'), /data-default-country="EG"/);
    assert.doesNotMatch(read('public/trainer-workspace.html'), /data-default-country="EG"/);
    const script = read('public/js/core/phone-inputs.js');
    assert.match(script, /\/api\/phone\/countries/);
    assert.match(script, /data-phone-country/);
    assert.match(script, /normalizeForTransport/);
    assert.match(script, /validateInput/);
    assert.match(script, /setCustomValidity/);
    assert.match(script, /phone-input-error/);
    assert.match(script, /countryFlag/);
    assert.match(script, /countryFlagUrl/);
    assert.match(script, /renderCountryFlag/);
    assert.match(script, /flagcdn\.com/);
    assert.match(script, /phone-country-flag/);
    assert.match(script, /phone-country-menu/);
    assert.match(script, /phone-country-option/);
    assert.match(script, /phone-country-trigger/);
    assert.match(script, /phone-country-divider/);
    assert.match(script, /phone-number-control/);
    assert.match(script, /phone-number-icon/);
    assert.match(script, /phone-number-divider/);
    assert.match(script, /phone-input-help/);
    assert.match(script, /tooLong/);
    assert.match(script, /phoneValidationBlocked/);
    assert.match(script, /exampleNational/);
    assert.match(script, /countryInputExample/);
    assert.match(script, /approximateCountry/);
    assert.match(script, /TIMEZONE_COUNTRY_MAP/);
    assert.match(script, /phoneCountrySource/);
    assert.match(script, /countryCodeForInput/);
    assert.match(script, /inputLimits/);
    assert.match(script, /syncNativeInputLimit/);
    assert.match(script, /projectedInputValue/);
    assert.match(script, /exceedsInputLimit/);
    assert.match(script, /phoneRejectedLimit/);
    assert.match(script, /maximumInputDigits/);
    assert.doesNotMatch(script, /localDigits\(country\?\.dialCode/);
    assert.match(script, /phoneMaximumDigits/);
    assert.match(script, /inputMode = 'numeric'/);
    assert.match(script, /setAttribute\('inputmode', 'numeric'\)/);
    assert.match(script, /setAttribute\('pattern', '\[0-9\+\\\\s\(\)\.\-\]\*'\)/);
    assert.match(script, /beforeinput/);
    assert.match(script, /clipboardData/);
    assert.match(read('public/css/components/phone-inputs.css'), /grid-template-columns: minmax\(8\.8rem/);
    assert.match(read('public/css/components/phone-inputs.css'), /grid-template-areas/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-number-control/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-number-icon/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-number-divider/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-input-help/);
    assert.match(read('public/css/components/phone-inputs.css'), /min-height: 2\.75rem/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-country-flag-image/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-country-flag/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-country-menu/);
    assert.match(read('public/css/components/phone-inputs.css'), /phone-country-option/);
    assert.match(read('public/js/app.js'), /LogicFitPhoneInputs\?\.validateInput/);
    const auth = read('src/middleware/auth.middleware.js');
    assert.match(auth, /request\.path === '\/phone\/countries'/);
    assert.match(auth, /request\.path === '\/phone\/country'/);
    assert.match(auth, /phoneCatalogPath/);
    assert.match(script, /\/api\/phone\/country/);
    assert.match(script, /loadDetectedCountry/);
    assert.match(script, /countryDetectionPromise/);
    assert.match(script, /phoneCountryGeneration/);
    assert.match(script, /applyCountrySelection\(input, select, detectedIso, 'ip'\)/);
    assert.match(read('src/config/env.js'), /PHONE_IP_GEOLOCATION_URL/);
    assert.match(read('src/config/env.js'), /PHONE_IP_GEOLOCATION_TIMEOUT_MS/);
    assert.match(read('.env.example'), /PHONE_IP_GEOLOCATION_URL=https:\/\/ipapi\.co\/\{ip\}\/country\//);
});

test('phone-bearing screens use tel inputs without changing numeric business fields', () => {
    const index = read('public/index.html');
    assert.match(index, /id="phone" type="tel"[^>]*data-phone-input/);
    assert.match(index, /id="attendancePhone" type="tel"[^>]*data-phone-input/);
    assert.match(index, /id="dayPassVisitorPhone" type="tel"[^>]*data-phone-input/);
    assert.match(index, /id="storeSupplierPhone" type="tel"[^>]*data-phone-input/);
    assert.match(index, /id="storeSupplierPhone"[^>]*data-phone-allow-fixed-line="true"/);
    assert.match(index, /id="brandingDocumentPhone"[^>]*data-phone-allow-fixed-line="true"/);
    assert.match(index, /id="externalPhone" type="tel"[^>]*data-phone-input/);
    assert.match(read('public/js/branch-context.js'), /id="branchPhoneInput"[^>]*type="tel"[^>]*data-phone-input[^>]*data-phone-allow-fixed-line="true"/);
    assert.match(read('public/js/pages/coaching/coaching.js'), /id="coachingEditPhone"[^>]*type="tel"[^>]*data-phone-input/);
    assert.match(read('public/js/trainer-workspace.js'), /phoneCountry/);
    assert.match(index, /id="amountPaid"[^>]*type="number"/);
});

test('phone writes use centralized normalization and tenant-scoped duplicate checks', () => {
    const member = read('src/services/member-service.js');
    const coaching = read('src/services/coaching-service.js');
    const attendance = read('src/services/attendance-service.js');
    const registration = read('src/services/gym-registration-service.js');
    assert.match(member, /normalizeInternationalPhone\(output\.phone/);
    assert.match(member, /WHERE tenant_id=@tenantId/);
    assert.match(member, /phoneNormalized/);
    assert.match(coaching, /normalizeInternationalPhone\(phone/);
    assert.match(coaching, /WHERE tenant_id=@tenantId/);
    assert.match(attendance, /tenant_id=@tenantId/);
    assert.match(registration, /normalizeMobile/);
    assert.doesNotMatch(registration, /defaultCountryCode\s*=\s*['"]20['"]/);
    assert.match(registration, /requireCountryForLocal:\s*true/);
});
